server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      schema:
        - data.sql
        - schema.sql
    jndi-name: java:/comp/env/jdbc/tacoCloudDS
  data:
    rest:
      base-path: /api
  artemis:
    broker-url: tcp://activemq.tacocloud.com
    user: tacoweb
    password: l3tm31n

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

taco:
  orders:
    pageSize: 10
