server:
  port: 80

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      schema:
        - data.sql
        - schema.sql
    jndi-name: java:/comp/env/jdbc/tacoCloudDS
  jms:
    template:
      default-destination: tacocloud.order.queue

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

taco:
  orders:
    pageSize: 10
